version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Run Maven integration tests
          command: |
            chmod +x ./mvnw
            ./mvnw --batch-mode clean verify

workflows:
  test:
    jobs:
      - test
